services:
  spacetime-server:
    image: spacetime-server
    build:
      context: .
      dockerfile: Dockerfile.server
    volumes:
      - ./server:/app/server
      - ./client:/app/client
    working_dir: /app
    entrypoint: [ "sh", "-c" ]
    command: >
      "
        spacetime start & sleep 3 &&
        spacetime generate --lang typescript --out-dir ./client/src/module_bindings --project-path ./server  &&
        spacetime publish  -y --anonymous --project-path ./server drawamare &&
        wait
      "
    ports:
      - "3000:3000"

  client:
    image: drawamare-client
    build:
      context: ./client
      dockerfile: ../Dockerfile.client
    command:  sh -c "npm install && npm run start"
    volumes:
      - ./client:/app
    working_dir: /app
    ports:
      - "8080:8080"
