// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import CreateLayerReducer from "../create_layer_reducer";
import DeleteLayerReducer from "../delete_layer_reducer";
import RenameLayerReducer from "../rename_layer_reducer";
import SaveLayerReducer from "../save_layer_reducer";
import SendCommandReducer from "../send_command_reducer";
import SetNameReducer from "../set_name_reducer";

export type CreateLayerParams = __Infer<typeof CreateLayerReducer>;
export type DeleteLayerParams = __Infer<typeof DeleteLayerReducer>;
export type RenameLayerParams = __Infer<typeof RenameLayerReducer>;
export type SaveLayerParams = __Infer<typeof SaveLayerReducer>;
export type SendCommandParams = __Infer<typeof SendCommandReducer>;
export type SetNameParams = __Infer<typeof SetNameReducer>;

