// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import {
  AlgebraicType,
  AlgebraicValue,
  BinaryReader,
  BinaryWriter,
  CallReducerFlags,
  ConnectionId,
  DbConnectionBuilder,
  DbConnectionImpl,
  DbContext,
  ErrorContextInterface,
  Event,
  EventContextInterface,
  Identity,
  ProductType,
  ProductTypeElement,
  ReducerEventContextInterface,
  SubscriptionBuilderImpl,
  SubscriptionEventContextInterface,
  SumType,
  SumTypeVariant,
  TableCache,
  TimeDuration,
  Timestamp,
  deepEqual,
} from "@clockworklabs/spacetimedb-sdk";
import { Point as __Point } from "./point_type";
import { StrokeStyle as __StrokeStyle } from "./stroke_style_type";

export type DrawCommand = {
  commandType: string,
  layerId: string,
  blendMode: string | undefined,
  pos: __Point,
  strokeStyle: __StrokeStyle,
};

/**
 * A namespace for generated helper functions.
 */
export namespace DrawCommand {
  /**
  * A function which returns this type represented as an AlgebraicType.
  * This function is derived from the AlgebraicType used to generate this type.
  */
  export function getTypeScriptAlgebraicType(): AlgebraicType {
    return AlgebraicType.createProductType([
      new ProductTypeElement("commandType", AlgebraicType.createStringType()),
      new ProductTypeElement("layerId", AlgebraicType.createStringType()),
      new ProductTypeElement("blendMode", AlgebraicType.createOptionType(AlgebraicType.createStringType())),
      new ProductTypeElement("pos", __Point.getTypeScriptAlgebraicType()),
      new ProductTypeElement("strokeStyle", __StrokeStyle.getTypeScriptAlgebraicType()),
    ]);
  }

  export function serialize(writer: BinaryWriter, value: DrawCommand): void {
    DrawCommand.getTypeScriptAlgebraicType().serialize(writer, value);
  }

  export function deserialize(reader: BinaryReader): DrawCommand {
    return DrawCommand.getTypeScriptAlgebraicType().deserialize(reader);
  }

}


