// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const Brush = __t.object("Brush", {
  ratio: __t.f32(),
  spikes: __t.i32(),
  density: __t.i32(),
  spacing: __t.f32(),
  angle: __t.i32(),
  shape: __t.string(),
  brushType: __t.string(),
  vFade: __t.i32(),
  hFade: __t.i32(),
  texture: __t.option(__t.string()),
});
export type Brush = __Infer<typeof Brush>;

export const Command = __t.object("Command", {
  id: __t.i32(),
  layer: __t.i32(),
  owner: __t.identity(),
  get commands() {
    return __t.array(DrawCommand);
  },
});
export type Command = __Infer<typeof Command>;

export const DrawCommand = __t.object("DrawCommand", {
  commandType: __t.string(),
  blendMode: __t.option(__t.string()),
  get pos() {
    return __t.option(Point);
  },
  get strokeStyle() {
    return __t.option(StrokeStyle);
  },
  startWidth: __t.option(__t.i32()),
  endWidth: __t.option(__t.i32()),
  get brush() {
    return Brush;
  },
});
export type DrawCommand = __Infer<typeof DrawCommand>;

export const Layer = __t.object("Layer", {
  id: __t.i32(),
  name: __t.option(__t.string()),
  owner: __t.identity(),
  base64: __t.option(__t.string()),
  forceUpdate: __t.bool(),
});
export type Layer = __Infer<typeof Layer>;

export const Point = __t.object("Point", {
  x: __t.i32(),
  y: __t.i32(),
});
export type Point = __Infer<typeof Point>;

export const StrokeStyle = __t.object("StrokeStyle", {
  width: __t.f32(),
  cap: __t.string(),
  color: __t.i32(),
  alpha: __t.f32(),
});
export type StrokeStyle = __Infer<typeof StrokeStyle>;

export const User = __t.object("User", {
  identity: __t.identity(),
  name: __t.option(__t.string()),
  online: __t.bool(),
});
export type User = __Infer<typeof User>;

